"""Create initial tables

Revision ID: e7833b45281f
Revises:
Create Date: 2026-01-10 15:21:04.193304

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7833b45281f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("create schema billing")
    op.execute("create schema following")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_topics_count", sa.Integer(), nullable=False),
        sa.Column(
            "subscription_tier",
            sa.Enum("FREE", "PREMIUM", name="subscriptiontier"),
            nullable=False,
        ),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="billing",
    )
    op.create_index(
        op.f("ix_billing_users_created_topics_count"),
        "users",
        ["created_topics_count"],
        unique=False,
        schema="billing",
    )
    op.create_index(
        op.f("ix_billing_users_discarded"),
        "users",
        ["discarded"],
        unique=False,
        schema="billing",
    )
    op.create_index(
        op.f("ix_billing_users_subscription_tier"),
        "users",
        ["subscription_tier"],
        unique=False,
        schema="billing",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("followed_topics_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="following",
    )
    op.create_index(
        op.f("ix_following_users_discarded"),
        "users",
        ["discarded"],
        unique=False,
        schema="following",
    )
    op.create_index(
        op.f("ix_following_users_followed_topics_count"),
        "users",
        ["followed_topics_count"],
        unique=False,
        schema="following",
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["billing.users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id"),
        schema="billing",
    )
    op.create_index(
        op.f("ix_billing_topics_discarded"),
        "topics",
        ["discarded"],
        unique=False,
        schema="billing",
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("followers_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["following.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="following",
    )
    op.create_index(
        op.f("ix_following_topics_discarded"),
        "topics",
        ["discarded"],
        unique=False,
        schema="following",
    )
    op.create_index(
        op.f("ix_following_topics_followers_count"),
        "topics",
        ["followers_count"],
        unique=False,
        schema="following",
    )
    op.create_table(
        "follows",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("is_following", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["following.topics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["following.users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "topic_id"),
        schema="following",
    )
    op.create_index(
        op.f("ix_following_follows_is_following"),
        "follows",
        ["is_following"],
        unique=False,
        schema="following",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_following_follows_is_following"),
        table_name="follows",
        schema="following",
    )
    op.drop_table("follows", schema="following")
    op.drop_index(
        op.f("ix_following_topics_followers_count"),
        table_name="topics",
        schema="following",
    )
    op.drop_index(
        op.f("ix_following_topics_discarded"), table_name="topics", schema="following"
    )
    op.drop_table("topics", schema="following")
    op.drop_index(
        op.f("ix_billing_topics_discarded"), table_name="topics", schema="billing"
    )
    op.drop_table("topics", schema="billing")
    op.drop_index(
        op.f("ix_following_users_followed_topics_count"),
        table_name="users",
        schema="following",
    )
    op.drop_index(
        op.f("ix_following_users_discarded"), table_name="users", schema="following"
    )
    op.drop_table("users", schema="following")
    op.drop_index(
        op.f("ix_billing_users_subscription_tier"), table_name="users", schema="billing"
    )
    op.drop_index(
        op.f("ix_billing_users_discarded"), table_name="users", schema="billing"
    )
    op.drop_index(
        op.f("ix_billing_users_created_topics_count"),
        table_name="users",
        schema="billing",
    )
    op.drop_table("users", schema="billing")
    # ### end Alembic commands ###

    subscriptiontier = sa.Enum("FREE", "PREMIUM", name="subscriptiontier")
    subscriptiontier.drop(op.get_bind())

    op.execute("drop schema following")
    op.execute("drop schema billing")
